// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN-01UuCTyqyJLLkcmsVwbuw__KyMGDh4',
    appId: '1:617216773506:web:14c86bdcd9e8b876ce139b',
    messagingSenderId: '617216773506',
    projectId: 'test-app-7cd31',
    authDomain: 'test-app-7cd31.firebaseapp.com',
    storageBucket: 'test-app-7cd31.appspot.com',
    measurementId: 'G-4PGHHZNFS8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5V9rKULa49-Wh3Jz9ViFx6GSNKCVUQy4',
    appId: '1:617216773506:android:56fe1a8608d68eaece139b',
    messagingSenderId: '617216773506',
    projectId: 'test-app-7cd31',
    storageBucket: 'test-app-7cd31.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1lDAd73D46ojEXsjHSbfb0_OtLSMwZNA',
    appId: '1:617216773506:ios:59ff0a817187be5dce139b',
    messagingSenderId: '617216773506',
    projectId: 'test-app-7cd31',
    storageBucket: 'test-app-7cd31.appspot.com',
    iosBundleId: 'com.example.liveasyLogisticsAssignmentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1lDAd73D46ojEXsjHSbfb0_OtLSMwZNA',
    appId: '1:617216773506:ios:a9fe39a25e13c0b6ce139b',
    messagingSenderId: '617216773506',
    projectId: 'test-app-7cd31',
    storageBucket: 'test-app-7cd31.appspot.com',
    iosBundleId: 'com.example.liveasyLogisticsAssignmentApp.RunnerTests',
  );
}
